# Wordpress Openlitespeed
#
# Dont forget to install the Redis Object Cache plugin: https://wordpress.org/plugins/redis-cache/
# Add this to wp-config.php and activate it:
#   define( 'WP_REDIS_HOST', 'redis' );
# 
# Dont forget to install the Litespeed cache plugin: https://wordpress.org/plugins/litespeed-cache/
# Activate it and Apply a caching preset.


# Migrate tips:
# update wp_options set option_value='https://newdomain.nl' where option_name='home';
# update wp_options set option_value='https://newdomain.nl' where option_name='siteurl';

version: '3.1'
services:
  wordpress:
    # dont forget to update zzz-custom-php.ini path below, if you change this tag to a different php version:
    image: litespeedtech/openlitespeed:1.8.1-lsphp82


    restart: unless-stopped

    labels:
      - traefik.enable=true

      #https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=${TRAEFIK_RULE}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=myzerossl 
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true

      # add X-forwarded headers
      # - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers-forwarded.headers.customrequestheaders.X-Forwarded-Proto=https
      # - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.middlewares=${COMPOSE_PROJECT_NAME}-headers-forwarded
      
      # service port
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.service=${COMPOSE_PROJECT_NAME}
      
    ports:
     - 127.0.0.1:${HTTP_PORT}:80

    volumes:
      - wordpress:/var/www/vhosts/localhost/html
      # see https://github.com/litespeedtech/ols-docker-env/issues/77
      - logs:/usr/local/lsws/logs/
      - /root/portainer-templates/wordpress-ols/zzz-custom-php.ini:/usr/local/lsws/lsphp82/etc/php/8.2/mods-available/zzz-custom-php.ini


    networks:
      - proxynet
      - default

  db:
    image: mysql:8.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
     - 127.0.0.1:${MYSQL_PORT}:3306

  smtp:
    image: mwader/postfix-relay
    environment: 
      - POSTFIX_myhostname=${POSTFIX_HOSTNAME}

    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped


  gulp:
    build: ./build/gulp
    profiles:
      - dev
    volumes:
      - wordpress:/repo
    ports:
      - 127.0.0.1:${GULP_PORT}:3001
    stop_grace_period: 0s
    restart: unless-stopped

networks:
  proxynet:
    name: proxynet

volumes:
  wordpress:
    driver: zfs
  db:
    driver: zfs
  logs:
    driver: zfs
    