# Symfony Openlitespeed
#
# Mail smtp host should be mail, and port 25 with authtentication. And setup the shared mail-stack.



# Migrate tips:
# update wp_options set option_value='https://newdomain.nl' where option_name='home';
# update wp_options set option_value='https://newdomain.nl' where option_name='siteurl';

services:
  web:
    # dont forget to update zzz-custom-php.ini path below, if you change this tag to a different php version:
    image: litespeedtech/openlitespeed:${OLS_VERSION}

       

    restart: unless-stopped

    labels:
      - traefik.enable=true

      #https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=${TRAEFIK_RULE}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=myzerossl 
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true

      # add X-forwarded headers
      # - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-headers-forwarded.headers.customrequestheaders.X-Forwarded-Proto=https
      # - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.middlewares=${COMPOSE_PROJECT_NAME}-headers-forwarded
      
      # service port
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.service=${COMPOSE_PROJECT_NAME}
      
    ports:
     - 127.0.0.1:${HTTP_PORT}:80

    volumes:
      - web:/var/www/vhosts/localhost/html
      # see https://github.com/litespeedtech/ols-docker-env/issues/77
      - logs:/usr/local/lsws/logs/
      - ./symfony-ols/httpd_config.conf:/usr/local/lsws/conf/httpd_config.conf
      - ./symfony-ols/docker.conf:/usr/local/lsws/conf/templates/docker.conf



    networks:
      - proxynet
      - dbnet
      - default

  db:
    # image: mysql:8.2
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
     - 127.0.0.1:${MYSQL_PORT}:3306
    profiles:
      - db


networks:
  proxynet:
    name: proxynet
  dbnet:
    name: dbnet


volumes:
  web:
    driver: zfs
  logs:
    driver: zfs
  db:
    driver: zfs
    