# Core environment to use the other templates with.
# Its a treafik + portainer + watchdog stack.
# Use on Alpinbox with ZFS docker volume support.

# https://raw.githubusercontent.com/psy0rz/portainer-templates/main/templates.json

# Treafik dashboard is on https://host/treafik/dashboard

version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    restart: unless-stopped

    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=proxynet"
      - "--providers.docker.defaultRule="
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ZEROSSL_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myzerossl.acme.email=${ZEROSSL_EMAIL}"
      - "--certificatesresolvers.myzerossl.acme.storage=/storage/acme.json"
      - "--certificatesresolvers.myzerossl.acme.caserver=${ZEROSSL_CASERVER}"
      - "--certificatesresolvers.myzerossl.acme.eab.kid=${ZEROSSL_KID}" 
      - "--certificatesresolvers.myzerossl.acme.eab.hmacEncoded=${ZEROSSL_HMAC}"
      - "--certificatesresolvers.myzerossl.acme.httpChallenge.entryPoint=web"
      - "--accessLog"

      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5,10"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"

      # - "--experimental.otlpLogs=true"
      # - "--accesslog.otlp.grpc=true"
      # - "--accesslog.otlp.grpc.endpoint=stats-vl-1:4317"
      # - "--accesslog.otlp.grpc.insecure=true"

      - "--experimental.otlpLogs=true"
      - "--accesslog.otlp.http=true"
      - "--accesslog.otlp.http.endpoint=http://vl:9428/insert/opentelemetry/v1/logs"


      # - "--tracing=true"
      # - "--tracing.otlp.grpc=true"
      # - "--tracing.addInternals=true"
      # - "--tracing.otlp.grpc=true"
      # - "--tracing.otlp.grpc.endpoint=stats.server.bla:4317"
      # - "--tracing.otlp.grpc.insecure=true"





    ports:
      - "80:80"
      - "443:443"

    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
     - traefik:/storage

    networks:
      - proxynet
      - default

    labels:
      # Traefik status page
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard.rule=Host(`${DOMAIN}`) && ( PathPrefix(`/traefik`) || HeaderRegexp(`Referer`, `/traefik`) )"
      - "traefik.http.routers.dashboard.priority=999"
      - "traefik.http.routers.dashboard.middlewares=strip-traefik"
      - "traefik.http.middlewares.strip-traefik.stripprefix.prefixes=/traefik"

      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.service=dashboard"
      - "traefik.http.routers.dashboard.tls.certresolver=myzerossl"

      # redirect all http to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`.*`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.routers.http-catchall.priority=-1
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      # Router specifically for xmlrpc.php to block it globally (wordpress)
      - traefik.http.routers.xmlrpc.rule=PathPrefix(`/xmlrpc.php`)
      - traefik.http.routers.xmlrpc.priority=1000
      - traefik.http.routers.xmlrpc.tls=true


    stop_grace_period: 0s


  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock --admin-password ${PORTAINER_ADMIN_PASSWORD}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls.certresolver=myzerossl"

    stop_grace_period: 0s

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  maintenance:
    image: wickerlabs/maintenance
    restart: unless-stopped
    environment:
      TEAM_NAME: "Uw web team"
      HEADLINE: "Website onderhoud"
      TITLE: "Website onderhoud"
      MAIL_ADDRESS: "info@datux.nl"
      # LINK_COLOR: "#dc8100"
      # THEME: "Light"
      PORT: 8080
      RESPONSE_CODE: "503 Service Unavailable"
      MESSAGE: "In verband met onderhoud is deze site tijdelijk onbereikbaar. Als dit probleem aanhoudt, neem dan contact met ons op."
      CONTACT_LINK: "neem contact op"

    labels:
      - traefik.enable=true
      # catch all for when containers are down for maintanance:
      - traefik.http.routers.https-catchall.rule=hostregexp(`.*`)
      - traefik.http.services.https-catchall.loadbalancer.server.port=8080
      - traefik.http.routers.https-catchall.entrypoints=websecure
      - traefik.http.routers.https-catchall.tls=true
      - traefik.http.routers.https-catchall.priority=-1


    stop_grace_period: 0s


    networks:
      - proxynet
      - default

  # templates:
  #   image: nginx:alpine
  #   volumes:
  #     - ..:/usr/share/nginx/html/


networks:
  proxynet:
    name: proxynet

volumes:
 traefik:
   driver: zfs
 portainer:
   driver: zfs


