# Vanilla wordpress 
#
# Dont forget to install the Redis Object Cache plugin: https://wordpress.org/plugins/redis-cache/
# Add this to wp-config.php:
#   define( 'WP_REDIS_HOST', 'redis' );
#
# Add a wordpress mail-plugin to use the host 'mail' to mail, on port 25, without authentication. And setup the mail-stack.
#
# Migrate tips:
# update wp_options set option_value='https://newdomain.nl' where option_name='home';
# update wp_options set option_value='https://newdomain.nl' where option_name='siteurl';

version: '3.1'
services:
  wordpress:
    

    image: wordpress

    restart: unless-stopped

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_

    labels:
      - traefik.enable=true
      
      #https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=${TRAEFIK_RULE}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=myzerossl 
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true

    volumes:
      - wordpress:/var/www/html
    networks:
      - proxynet
      - dbnet
      - default


    ports:
     - 127.0.0.1:${HTTP_PORT}:80

  db:
    # image: mysql:8.2
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
     - 127.0.0.1:${MYSQL_PORT}:3306
    profiles:
      - db
    

  gulp:
    build: /root/portainer-templates/wordpress-ols/build/gulp
    profiles:
      - dev
    volumes:
      - wordpress:/repo
    ports:
      - 127.0.0.1:${GULP_PORT}:3001
    stop_grace_period: 0s
    restart: unless-stopped


  # smtp:
  #   image: mwader/postfix-relay
  #   environment: 
  #     - POSTFIX_myhostname=${POSTFIX_HOSTNAME}

  #   restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    

networks:
  proxynet:
    name: proxynet
  dbnet:
    name: dbnet

volumes:
  wordpress:
    driver: zfs
  db:
    driver: zfs
