# Vanilla GRAV cms
---
version: "2.1"
services:
  grav:
    
    image: lscr.io/linuxserver/grav:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # werkt nog niet door php.ini etc
      # - GRAV_ENVIRONMENT=production
      # - S6_KEEP_ENV=1
    volumes:
      - config:/config
    restart: unless-stopped
    stop_grace_period: 0s

    labels:
      - traefik.enable=true
      
      #https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=${TRAEFIK_RULE}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=myzerossl 
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true


    networks:
      - proxynet
      - default


    ports:
     - 127.0.0.1:${HTTP_PORT}:80

  smtp:
    image: mwader/postfix-relay
    environment: 
      - POSTFIX_myhostname=${POSTFIX_HOSTNAME}

    restart: unless-stopped
    stop_grace_period: 0s

networks:
  proxynet:
    name: proxynet


volumes:
  config:
    driver: zfs
