# Mailchannels relay

services:

  mail:
    hostname: mail
    image: mwader/postfix-relay

    environment: 

      - POSTFIX_myhostname=${POSTFIX_HOSTNAME}
      - POSTFIX_relayhost=smtp.mailchannels.net
      - POSTFIX_smtp_sasl_auth_enable=yes
      - POSTFIX_smtp_sasl_password_maps=static:${MAILCHANNELS_USER}:${MAILCHANNELS_PASSWORD}

      - POSTFIX_smtp_sasl_security_options=noanonymous
      - POSTFIX_smtpd_sasl_authenticated_header=yes
      - POSTFIX_smtp_tls_security_level=encrypt
      - POSTFIX_header_checks=regexp:/etc/postfix/header_checks
      - "POSTMAP_header_checks=/^From:\\s*(.+)$/    PREPEND X-AuthUser: $1"
      # - POSTFIX_debug_peer_level=1000
      # - POSTFIX_debug_peer_list=smtp.mailchannels.net


    restart: unless-stopped
    networks:
      - proxynet
      - default


networks:
  proxynet:
    name: proxynet

# volumes:
#   wordpress:
#     driver: zfs
#   db:
#     driver: zfs

